name: 'AutoUpdate'
 
on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Run autoupdate.sh'
        run: bash ./autoupdate.sh


